package com.elisvobs.roots.model;

import com.elisvobs.roots.R;

public class Recipes {
    public static String [] names = new String [] {
            "Sadza",
            "Sadza Rezviyo",
            "Mowa",
            "Mowa in Peanut Butter",
            "Mutsine",
            "Nyevhe",
            "Dried Nyevhe",
            "Muboora",
            "Nhanga",
            "Nhopi",
            "Makwaya",
            "Nyenje",
            "Derere Rechipudzi",
            "Okra Soup",
            "Derere Renama",
            "Nyamatepo",
            "Bupwe",
            "Tsunga",
            "Munyemba",
            "Nyemba",
            "Legume Buns",
            "Cowpea Fritters",
            "Rupiza",
            "Mutakura",
            "Mushroom",
            "Nhedzi",
    };

    public static int [] resourceIds = new int []{
            R.drawable.crepes,
            R.drawable.pancakes,
            R.drawable.scones,
            R.drawable.french_toast,
            R.drawable.muffins,
            R.drawable.waffles,
            R.drawable.toast,
            R.drawable.banana_bread,
            R.drawable.german_pancakes,
            R.drawable.beignets,
            R.drawable.blintzes,
            R.drawable.croissants,
            R.drawable.biscuits,
            R.drawable.cinnamon_rolls,
            R.drawable.coffee_cake,
            R.drawable.donut_holes,
            R.drawable.bagels,
            R.drawable.cupcakes,
            R.drawable.cupcakes,
            R.drawable.cupcakes,
            R.drawable.baguette,
            R.drawable.danish,
            R.drawable.danish,
            R.drawable.danish,
            R.drawable.danish,
            R.drawable.danish
    };

    public static String [] ingredients = new String []{
            "Maize meal/Cassava Flour`Water",
            "Sorghum/Millet/Wheat meal`Water",
            "Mowa leaves`Water`Cooking oil`Salt`Tomatoes",
            "Mowa leaves`Water`Peanut Butter`Salt`Tomatoes",
            "Black jack leaves`Tomatoes`Onions`Cooking Oil`Dash of salt`Water",
            "Fresh nyevhe leaves`Water`Salt`Bicarbonate of soda/utyora`Onions`Tomatoes`dash of salt`Cooking oil",
            "Dried nyevhe`Water`Salt`Bicarbonate of soda/utyora`Onions`Tomatoes`dash of salt`Peanut Butter",
            "Muboora leaves`Water`Salt`Bicarbonate of soda/utyora`Tomatoes`Cooking oil/Peanut Butter",
            "Nhanga`Water`(Salt optional)",
            "Manhanga/mashamba`Water`Salt`Peanut butter`Sorghum/millet/maize meal`(Sugar optional)",
            "Pumpkin seeds`Water`Salt",
            "Nyenje leaves`Salt`Soda/utyora`Tomatoes",
            "Okra`Water`Salt`Soda`Tomatoes",
            "Okra`Water`Salt`Flour`Peanut butter",
            "Derere leaves`Water`Salt`Soda/utyora`Tomatoes",
            "Fresh nyamatepo leaves`Water`Salt`Soda/utyora`Tomatoes",
            "Dried bupwe leaves`Water`Salt`Soda/utyora`Tomatoes",
            "Tsunga leaves`Water`Peanut butter`Salt`Tomatoes",
            "Dried nyemba leaves`Water`Cooking oil`Salt`Soda/utyora`Tomatoes`Flavouring",
            "Dried nyemba beans`Water`Cooking oil`Onions`Tomatoes`Flavouring",
            "Nyemba/nyimo flour`Wheat flour`Maize-meal`Salt`Sugar`Cooking`Milk",
            "Nyemba beans`Flour`Eggs`Salt`Sugar`Milk`Coking oil`Water",
            "Dried nyemba beans`Peanut butter`Salt`Water",
            "Dried nyemba beans`Dried groundnuts`Dried nyimo`Maize grits`Water`Salt`Peanut butter",
            "Fresh or dried mushroom`Water`Cooking oil`Salt`Onions",
            "Nhedzi/Tsvuketsvuke/Chihombiro`Salt`Water`Tomatoes`Peanut butter",
    };

    public static String [] directions = new String [] {
            "Boil clean water.`Add small quantities of maize meal and stir.`Continue adding mealie meal and stirring, making sure there are no lumps until it becomes a thick porridge.`Let the porridge boil for ~15 - 20 minutes.`Add more mealie meal in small quantities and stir.`Stir till all the mealie meal has mixed into the porridge.`Reduce the heat and let sadza cook slowly.`Stir again a minutes before serving.",
            "Put ~150g of the millet/sorghum/wheat meal into the pot.`Add just enough cold water to make a paste.`Add boiling water ~700ml into the pot and stir whilst on the stove.`Bring it to the boil. (If it's too thick add more boiling water. If it's too thin, make a paste again in a separate plate then pour it into the pot).`As soon as it starts boiling, close pot, reduce heat. `Let it simmer for ~20 minutes.`Add the remaining millet meal a bit at a time, mixing well after each addition. `Then close the pot and let it simmer again for 5 minutes.`A few minutes before serving, stir again. `Serve warm with vegetables, beef, poultry, fish or sour milk",
            "Wash leaves in warm water.`Boil the leaves for not more than 10 minutes`Remove the leaves from the pot into a plate`Put cooking oil into the pot and heat for ~3 minutes`Remove excess water from vegetables and put them into pre-heated cooking oil`Add sliced tomatoes and mix lightly`Add flavouring and salt to taste`Add a small quantity of water`Boil for ~5 minutes",
            "Wash leaves in cold water`Put water and salt into saucepan and bring it to boil`Add leaves and boil till tender`Remove vegetables from saucepan`Boil sliced tomatoes till tender`Add peanut butter and stir with wooden spoon to make a thick paste`Add boiled vegetables and continue stirring`Reduce heat and simmer for ~5 - 7 minutes.",
            "Wash mutsine leaves in cold water and ensure that there is no soil.`Put mutsine leaves into the pot and add water.`Leave until the water has boiled then remove the water.`Place boiled leaves in a dish or plate.`In a pot pour cooking oil and let cooking oil heat.`Cut tomatoes and add into the heating cooking oil and stir.`Add mutsine leaves and stir as if cooking green vegetables.`Then add salt and onions. You can also add cayenne pepper or other spices.",
            "Place water, salt and soda in a saucepan and bring to boil.`Put nyevhe leaves in the saucepan and boil for about 2 hours without stirring (stirring causes bitterness).`When the leaves turn brown, stir with a wooden spoon.`Drain the vegetable stock and discard.`Place the drained vegetables in a bowl.`Put some oil in a saucepan and heat the oil.`Sauté sliced onions and fry until tender.`Add sliced tomatoes and stir.`Add nyevhe leaves, cover the pan and simmer for a few minutes.",
            "Soak in cold water for 30 minutes.`Drain the water.`Place water and salt in a saucepan and bring to the boil.`Put vegetables in the saucepan and boil for 30 minutes.`Remove vegetables from the saucepan leaving vegetable stock.`Place the drained vegetables in a bowl.`Add sliced tomatoes and boil for 3 minutes.`Add peanut butter and stir into a thick paste.`Add the vegetables to the paste and stir for 2 minutes.`Reduce heat and simmer for a further 3 - 5 minutes.",
            "1.\tPut water, soda and salt and bring to the boil.`2.\tAdd muboora leaves and boil for about 3 – 5 minutes.`4.\tAdd cooking oil to vegetables and stir for a minute.`5.\tUse the vegetable stock to adjust the consistency.`6.\tReduce heat and simmer for 3 - 5 minutes.`4.\tTo add peanut proceed from step 3 by adding sliced tomatoes to the vegetable stock.`5.\tBoil tomatoes until they are tender.`6.\tAdd boiled leaves and stir.`7.\tAdd peanut butter and boil for about 5 -7 minutes.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
            ".`.`.`.`.`.`.`..`.",
    };

    public static String [] nutrients = new String [] {
            "Health benefits of eating zviyo include helping with weight loss, lowering blood cholesterol levels, regulating blood sugar levels especially for those who suffer from diabetes"
    };

}