package com.elisvobs.roots.model;

import com.elisvobs.roots.R;

public class Recipes {
    public static String[] names = new String[] {
            "Sadza/Isitshwala",
            "Sadza Rezviyo",
            "Mowa/Imbuya",
            "Mowa in Peanut Butter",
            "Mutsine",
            "Nyevhe/Ulude",
            "Dried Nyevhe",
            "Muboora/Ibhobola",
            "Nhanga/Ithanga",
            "Nhopi/Inhopi",
            "Makwaya",
            "Mabumbe",
            "Nyenje/Idelele",
            "Derere Rechipudzi",
//            "Derere Rechipudzi/Idelele lamathanga",
            "Okra Soup",
            "Derere Renama",
//            "Derere Renama/Idelele inama",
            "Nyamatepo/Umdlothi",
            "Bupwe/Idelele",
            "Tsunga/Umbhida",
            "Munyemba",
            "Nyemba/Indumba",
            "Legume Buns",
            "Cowpea Fritters",
            "Rupiza",
            "Mutakura",
            "Howa/Amakhowa",
//            "Mushroom (Howa/Amakhowa)",
            "Nhedzi",
    };

    public static int[] resourceIds = new int[]{
            R.drawable.sadza,
            R.drawable.zviyo,
            R.drawable.amaranth,
            R.drawable.mowa,
            R.drawable.mutsine,
            R.drawable.nyevhi,
            R.drawable.nyevhib,
            R.drawable.muboora,
            R.drawable.nhanga,
            R.drawable.nhopi,
            R.drawable.makwaya,
            R.drawable.mabumbe,
            R.drawable.nyenje,
            R.drawable.okra,
            R.drawable.okrasoup,
            R.drawable.derere,
            R.drawable.nyamatepo,
            R.drawable.bupwe,
            R.drawable.tsunga,
            R.drawable.munyemba,
            R.drawable.nyemba,
            R.drawable.legume_bun,
            R.drawable.cpfritter,
            R.drawable.rupiza,
            R.drawable.mutakura,
            R.drawable.mushroom,
            R.drawable.nhedzi
    };

    public static String[] ingredients = new String[]{
            "Maize meal/Cassava Flour`Water",
            "Sorghum/Millet/Wheat meal`Water",
            "Mowa leaves`Water`Cooking oil`Salt`Tomatoes",
            "Mowa leaves`Water`Peanut Butter`Salt`Tomatoes",
            "Black jack leaves`Tomatoes`Onions`Cooking Oil`Dash of salt`Water",
            "Fresh nyevhe leaves`Water`Salt`Bicarbonate of soda/utyora`Onions`Tomatoes`dash of salt`Cooking oil",
            "Dried nyevhe`Water`Salt`Bicarbonate of soda/utyora`Onions`Tomatoes`dash of salt`Peanut Butter",
            "Muboora leaves`Water`Salt`Bicarbonate of soda/utyora`Tomatoes`Cooking oil/Peanut Butter",
            "Nhanga`Water`(Salt optional)",
            "Manhanga/mashamba`Water`Salt`Peanut butter`Sorghum/millet/maize meal`(Sugar optional)",
            "Pumpkin seeds`Water`Salt",
            "Sun-dried Pumpkin seeds`Water`Pumpkin leaves",
            "Nyenje leaves (fresh or dried)`Salt`Soda/utyora`Tomatoes",
            "Okra`Water`Salt`Soda`Tomatoes",
            "Okra`Water`Salt`Flour`Peanut butter",
            "Derere leaves`Water`Salt`Soda/utyora`Tomatoes",
            "Fresh nyamatepo leaves`Water`Salt`Soda/utyora`Tomatoes",
            "Dried bupwe leaves`Water`Salt`Soda/utyora`Tomatoes",
            "Tsunga leaves`Water`Peanut butter`Salt`Tomatoes",
            "Dried nyemba leaves`Water`Cooking oil`Salt`Soda/utyora`Tomatoes`Flavouring",
            "Dried nyemba beans`Water`Cooking oil`Onions`Tomatoes`Flavouring",
            "Nyemba/nyimo flour`Wheat flour`Maize-meal`Salt`Sugar`Cooking`Milk",
            "Nyemba beans`Flour`Eggs`Salt`Sugar`Milk`Coking oil`Water",
            "Dried nyemba beans`Peanut butter`Salt`Water",
            "Dried nyemba beans`Dried groundnuts`Dried nyimo`Maize grits`Water`Salt`Peanut butter",
            "Fresh or dried mushroom`Water`Cooking oil`Salt`Onions",
            "Nhedzi/Tsvuketsvuke/Chihombiro`Salt`Water`Tomatoes`Peanut butter",
    };

    public static String[] directions = new String[] {
            "Boil clean water.`Add small quantities of maize meal and stir.`Continue adding mealie meal and stirring, making sure there are no lumps until it becomes a thick porridge.`Let the porridge boil for ~15 - 20 minutes.`Add more mealie meal in small quantities and stir.`Stir till all the mealie meal has mixed into the porridge.`Reduce the heat and let sadza cook slowly.`Stir again a minutes before serving.",
            "Put ~150g of the millet/sorghum/wheat meal into the pot.`Add just enough cold water to make a paste.`Add boiling water ~700ml into the pot and stir whilst on the stove.`Bring it to the boil. (If it's too thick add more boiling water. If it's too thin, make a paste again in a separate plate then pour it into the pot).`As soon as it starts boiling, close pot, reduce heat. `Let it simmer for ~20 minutes.`Add the remaining millet meal a bit at a time, mixing well after each addition. `Then close the pot and let it simmer again for 5 minutes.`A few minutes before serving, stir again. `Serve warm with vegetables, beef, poultry, fish or sour milk",
            "Wash leaves in warm water.`Boil the leaves for not more than 10 minutes`Remove the leaves from the pot into a plate`Put cooking oil into the pot and heat for ~3 minutes`Remove excess water from vegetables and put them into pre-heated cooking oil`Add sliced tomatoes and mix lightly`Add flavouring and salt to taste`Add a small quantity of water`Boil for ~5 minutes",
            "Wash leaves in cold water`Put water and salt into saucepan and bring it to boil`Add leaves and boil till tender`Remove vegetables from saucepan`Boil sliced tomatoes till tender`Add peanut butter and stir with wooden spoon to make a thick paste`Add boiled vegetables and continue stirring`Reduce heat and simmer for ~5 - 7 minutes.",
            "Wash mutsine leaves in cold water and ensure that there is no soil.`Put mutsine leaves into the pot and add water.`Leave until the water has boiled then remove the water.`Place boiled leaves in a dish or plate.`In a pot pour cooking oil and let cooking oil heat.`Cut tomatoes and add into the heating cooking oil and stir.`Add mutsine leaves and stir as if cooking green vegetables.`Then add salt and onions. You can also add cayenne pepper or other spices.",
            "Place water, salt and soda in a saucepan and bring to boil.`Put nyevhe leaves in the saucepan and boil for about 2 hours without stirring (stirring causes bitterness).`When the leaves turn brown, stir with a wooden spoon.`Drain the vegetable stock and discard.`Place the drained vegetables in a bowl.`Put some oil in a saucepan and heat the oil.`Sauté sliced onions and fry until tender.`Add sliced tomatoes and stir.`Add nyevhe leaves, cover the pan and simmer for a few minutes.",
            "Soak in cold water for 30 minutes.`Drain the water.`Place water and salt in a saucepan and bring to the boil.`Put vegetables in the saucepan and boil for 30 minutes.`Remove vegetables from the saucepan leaving vegetable stock.`Place the drained vegetables in a bowl.`Add sliced tomatoes and boil for 3 minutes.`Add peanut butter and stir into a thick paste.`Add the vegetables to the paste and stir for 2 minutes.`Reduce heat and simmer for a further 3 - 5 minutes.",
            "1.\tPut water, soda and salt and bring to the boil.`2.\tAdd muboora leaves and boil for about 3 – 5 minutes.`4.\tAdd cooking oil to vegetables and stir for a minute.`5.\tUse the vegetable stock to adjust the consistency.`6.\tReduce heat and simmer for 3 - 5 minutes.`4.\tTo add peanut proceed from step 3 by adding sliced tomatoes to the vegetable stock.`5.\tBoil tomatoes until they are tender.`6.\tAdd boiled leaves and stir.`7.\tAdd peanut butter and boil for about 5 -7 minutes.",
            "Wash the pumpkin.`Slice the pumpkin and remove the seeds.`Put the sliced pumpkin into a saucepan with little water and boil till tender.`Salt may be added.`Serve warm or cold.",
            "Slice the pumpkin, peel it and remove the seeds.`Put the sliced pumpkin into a saucepan with little water and boil till tender, stirring constantly with a wooden spoon.`Add a little sorghum/millet/maize meal and mix thoroughly to make a thick paste.`Add a pinch of salt and peanut butter then continue to mix.`Reduce heat and simmer for 5 - 10 minutes.",
            "Roast the dried pumpkin seeds with a little water and salt.`Stir continuously until the water evaporates and the seeds are dry.",
            "Remove clean and sun-dried pumpkin seeds. Roast the seeds until brownish and pound the roasted seeds using pestle and mortar. Grind the seeds using grinding stones i.e. guyo and huyo like in peanut butter until a fine paste is obtained.`Add little water and mould into balls.`Consume with a vegetable or meat sauce",
            "Put water, soda, salt and sliced tomatoes in a saucepan and boil.`Stir vigorously and continuously with a wooden spoon for about 15 minutes.`Add sliced nyenje leaves and stir thoroughly.`Reduce heat and simmer for 3 - 5 minutes.",
            "Wash okra pods in cold water.`Cut the pods into thin slices.`Put water, salt and soda in a saucepan and bring to the boil.`Add the sliced pods and boil for about 15 minutes.`Add sliced tomatoes to the saucepan.`Stir the vegetables with a wooden for about 3 - 5 minutes.`Add salt to taste.`Serve warm or cold",
            "Slice the okra pods.`Put water, salt and soda in a saucepan and bring to the boil.`Add the sliced pods and boil until tender.`Mix a little water and flour in a bowl to make a thin slurry.`Add the mixture to the okra and stir with a wooden spoon.`Add peanut butter.`Reduce heat and simmer for 7 - 10 minutes.",
            "Cut the leaves into small pieces.`Put water, salt, soda and sliced tomatoes in a saucepan and boil.`Add derere leaves and stir for 10 - 15 minutes with a wooden spoon.`Serve warm or cold",
            "Cut the vegetable into small pieces.`Put water, salt, soda and sliced tomatoes in a saucepan and boil.`Add vegetables and stir with a wooden spoon.",
            "Pound the dried bupwe vegetables with pestle and mortar.`Put water, salt and soda in a saucepan and boil.`Add 1 tablespoon of the pounded vegetables and boil for 10 - 15 minutes (1 heaped tablespoon is enough for 4 to 6 servings).`Tomatoes can also be added.",
            "Cut the vegetables into small pieces.`Put water and salt in a saucepan and boil.`Add the vegetables and boil for about 15 - 20 minutes.`Drain off the water and throw it away (this reduces the bitter taste).`Put the vegetables in a bowl`Boil sliced tomatoes until tender.`Add peanut butter and stir into a thick paste.`Add the vegetables and stir for a minute.`Reduce the heat and simmer for 3 - 5 minutes.",
            "Put water, salt and soda in a saucepan and boil.`Add nyemba leaves and boil for 15 - 20 minutes.`Drain off the vegetables, put them in a bowl and keep the vegetable stock.`Heat the oil.`Fry sliced tomatoes until tender.`Add flavouring and stir with a wooden spoon for 2 minutes.`Add the vegetable stock and stir.`Reduce heat and simmer for 3 - 5 minutes.",
            "Put the dried nyemba beans in a bowl and remove any foreign particles.`Soak the beans overnight in cold water (this reduces the cooking time).`Put water in a saucepan and boil.`Add the beans and boil until tender.`Drain the stock and keep it.`Remove the beans and keep in a bowl.`Heat the oil.`Fry sliced onions until tender.`Add sliced tomatoes to the onions and stir until tomatoes are tender.`Add curry powder and stir.`Add the beans and salt and stir with a wooden spoon.`Add the stock and continue stirring.`Reduce the heat and simmer for 15 - 20 minutes.",
            "Mix the nyemba or nyimo flour with maize meal and wheat flour in a bowl.`Add sugar and salt to the mix.`Add the milk to the required thickness.`Heat the oil in a frying pan.`Spoon the mixture into the hot oil to make buns.`Turn until they are golden brown on both sides.`Repeat adding oil if necessary until the dough is finished.`Place buns in a container and serve when cool.`Serve with tea.",
            "Put water in a saucepan, add nyemba beans and boil until tender.`Mash the beans.`Add flour, salt and eggs and mix using a wooden spoon.`Add milk to the required thickness.`Heat the oil in a frying pan.`Spoon the dough into the hot oil.`Turn each fritter until golden brown on both sides.Repeat until the dough is finished`Place the fritters in a container.`Serve with tea.",
            "Roast the dried nyemba beans.`Grind to remove the outer skin.`Use mortar to crush the beans (do not grind to fine powder).`Put water in saucepan and bring to boil.`Add the crushed beans and boil for 2 - 3 hours till tender.`Add salt and peanut butter and stir with a wooden spoon.`Reduce heat and simmer for 15 - 20 minutes.",
            "Remove dirt from maize grits and soak overnight in cold water.`Remove foreign particles from groundnuts, cow peas and nyimo.`Put maize grits, nyemba, nyimo, groundnuts and water in a saucepan and boil for 2 - 3 hours or until tender and looking like a thick soup.`Add salt and peanut butter and mix.`Reduce heat and simmer for 15 - 20 minutes.",
            "Wash fresh mushrooms in cold water and let them drip dry (do not wash dried mushroom before cooking).`Heat the oil in a frying pan.`Fry cubed onions in th oil until brown.`Add mushrooms and stir gently for a minute.`Add salt, pepper or flavouring and mix.`Reduce the heat and simmer for 2 - 3 minutes.",
            "Soak the mushrooms in cold water for a minute.`Boil the mushrooms in salted water for a minute.`Drain the mushroom and put to one side.`Boil water in a saucepan.`Add sliced tomatoes and boil till tender.`Add peanut butter and stir with a wooden spoon until the paste is thick.`Add the mushroom and stir.`Reduce heat and simmer for 5 minutes.",
    };

//    public static String [] nutrients = new String [] {
//            "Health benefits of eating zviyo include helping with weight loss, lowering blood cholesterol levels, regulating blood sugar levels especially for those who suffer from diabetes"
//    };

}